### ISSUE TITLE
Snakefile, .gitignore, TODO.md, include_into_rpackage.txt within the template

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#2]
Then remove these files from .setup_config/touch_these_files.txt

**Comment by russHyde** [comment]
- [ ] Snakefile
- [ ] .gitignore
- [ ] TODO.md
- [ ] lib/conf/include_into_rpackage.txt
- [ ] .here

**Comment by russHyde** [comment]
`./doc/notebook.Rmd` should have a standard template:

```
---
title: "Project Title" // possibly taken from cookiecutter args
author: "Author Name" // taken from cookiecutter args - default arg "Russell Hyde"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
    pdf_document:
        latex_engine: xelatex // ? what was the reason for using xelatex ?
        number_sections: yes
        df_print: kable
        fig_caption: yes
        fig_width: 7 // or 3.2? - I typically used 4x7 and 7x7 for ggplot, 12x10 for heatmap
        fig_height: 7 // or 3.2?
        includes:
            in_header: "header.tex"
urlcolor: blue
---

```{r}
library(here)
```
        
```
