### ISSUE TITLE
consistency checks for results files

### ISSUE THREAD

**Issue by russHyde** [russHyde/data_buddy#28]
User can specify a range of checks to be performed on named results or data files

Purpose:

- Boss asks for `the top X results in experiment Y`
    - If I send these results on, and subsequently refactor the result-generating code in my analysis scripts (or add independent functionality), I want to know that restructuring the code does not alter the results obtained (at least for those X results) since experiments based on those results may be performed.
    - Also, if I replace the result-generating code (say, replacing edgeR with limma), I'd like to know if some aspect of those results is stable (eg, the top-10 genes may be setwise equal, but have different statistics)

Checks should be specified in yaml

```
test1:
    input_file: some_file
    expected_md5sum: xyz345.....

test2:
    input_file: some_other_file
    test_script: some_script.py
    test_args: "--head=10 --column=2 --sort"
    expected_file: "my_expected_results.[tsv|txt]" ## contains the second column from the first 10 lines
```
